production:
  stack: cedar
  app: jrubyconfeu2013-28
  config: &default
    BUNDLE_WITHOUT: "development:test"

staging:
  stack: cedar
  app: jrubyconfeu2013-staging-625
  config: &default
    BUNDLE_WITHOUT: "development:test"
